### PR TITLE
index.html: Update gallery images

### PR DESCRIPTION
**Pull request by illseption**
Updated with images from sfd16 

Fixes pulug#8

### CODE REVIEW

**Review by divyam3897 — COMMENTED** [review]
Why are there two commits in your PR? Can you only make your commit?

**Comment by illseption** [comment]
How do I remove that?? Its showing up automatically

**Comment by divyam3897** [comment]
what commands did you run? Can you copy the output of "git log" to https://pastebin.com/

**Comment by illseption** [comment]
https://pastebin.com/xD1gAM26

**Comment by divyam3897** [comment]
do "git log > patch.text" and copy all the contents from patch.text please.

**Comment by illseption** [comment]
its the same thing

**Comment by divyam3897** [comment]
you messed up things a little, clone afresh, make a branch using "git checkout -b branchName", make your changes, commit them, push them and create a PR again.

**Pull request closed without merging**
